Get customer endpoint
InformatikLK-LLG/mke pull request #19
Opened 2021-06-29 14:20 UTC by Mathis-Kuhl

Create customer, customer repository and customer controller.

2021-06-29 15:30 UTC, danieldietzler requested changes
Changes to UserController and yarn.lock should not be commited since they do not contribute anything to the issue.

2021-06-29 19:23 UTC, danieldietzler requested changes

2021-06-29 19:23 UTC, danieldietzler commented on server/src/main/java/de/llggiessen/mke/schema/Customer.java
> +    private Long customerId;
Primary Key should be called 'id'.

2021-06-29 19:23 UTC, danieldietzler commented on server/src/main/java/de/llggiessen/mke/repository/CustomerRepository.java
> +        @Modifying
The modifying annotation is not necessary here since the findAllByEmail Query does not modify anything.

2021-06-29 19:23 UTC, danieldietzler commented on server/src/main/java/de/llggiessen/mke/controller/CustomerController.java
> +    }
You should provide a GET endpoint, identified by the primary key ('id'), which returns the unique customer or throws a BAD REQUEST (400) http status otherwise.

2021-07-07 12:48 UTC, hfrank3n requested changes
Consider adding a method (+ endpoint) for deleting customers by their id, and not just by their email.

2021-07-09 15:06 UTC, hfrank3n requested changes

2021-07-09 15:06 UTC, hfrank3n commented on server/src/main/java/de/llggiessen/mke/repository/CustomerRepository.java
> +        @Query(value = "DELETE FROM customer WHERE customer.email = :email", nativeQuery = true)
Add @Modifying annotation to (modifying) delete queries.

2021-07-14 07:14 UTC, danieldietzler approved these changes

2021-07-14 07:15 UTC, merged